### ISSUE TITLE
New Forge gradio 4 support?

### ISSUE THREAD

**Issue by diodiogod** [nihedon/sd-webui-weight-helper#9]
The extension is no longer working with the new updated Forge. I would be very much grateful if it could be fixed. 
I actually don't think https://github.com/hako-mikan/sd-webui-lora-block-weight is working at all, but it doesn't have any new updates in 4 months =(

**Comment by nihedon** [comment]
@diodiogod 
Thank you for the report.
I’ve been away from Forge after hearing about the upcoming update. I’ll check the issue right away and fix it.
I’ll push an update by tomorrow.

**Comment by diodiogod** [comment]
Even if Lora Block weights are not working, I got so used to the pop up menu to adjust weight that, as I stated before, can't live without it 🤣
I was about to post the error, but forgot 

```
---
*** Error executing callback app_started_callback for J:\stablediffusion1111s2\Data\Packages\forge2\extensions\sd-webui-weight-helper\scripts\weight_helper.py
    Traceback (most recent call last):
      File "J:\stablediffusion1111s2\Data\Packages\forge2\modules\script_callbacks.py", line 256, in app_started_callback
        c.callback(demo, app)
      File "J:\stablediffusion1111s2\Data\Packages\forge2\extensions\sd-webui-weight-helper\scripts\weight_helper.py", line 22, in init_endpoints
        WeightHelperAPI.instance = WeightHelperAPI()
      File "J:\stablediffusion1111s2\Data\Packages\forge2\extensions\sd-webui-weight-helper\scripts\weight_helper.py", line 41, in __init__
        self.network = importlib.import_module("extensions-builtin.Lora.network")
      File "importlib\__init__.py", line 126, in import_module
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'extensions-builtin.Lora.network'

```

**Comment by nihedon** [comment]
@diodiogod 
I used Lora Block-weight a lot myself, so I’m also very sad that it hasn’t been updated...

Thank you so much for loving this extension. Your support really motivates me!
For now, I’ve fixed this extension to work with the New Forge. Please update to the latest version and give it a try.

**Comment by diodiogod** [comment]
Thanks! It's working now!! Let's hope block-weight gets updated in the future as well. But having the popup back is great!

**Comment by Krek12** [comment]
do I have to download the hako mikan extension? Or will it work without it?

**Comment by nihedon** [comment]
@Krek12 
Yes, you will need the hako mikan Lora Block Weight extension to use this extension. This is because it’s a tool for visually setting the Lora weights that can be configured with Lora Block Weight.

https://github.com/hako-mikan/sd-webui-lora-block-weight

**Comment by Krek12** [comment]
> @Krek12 Да, вам понадобится расширение Hako Mikan Lora Block Weight для использования этого расширения. Это потому, что это инструмент для визуальной настройки весов Lora, который можно настроить с помощью Lora Block Weight.
> 
> https://github.com/hako-mikan/sd-webui-lora-block-weight

then I don't know what's wrong with me. For the last couple of weeks I have been trying everything I have tried. I've even used different browsers. I still don't understand what's wrong.

**Comment by diodiogod** [comment]
> > @Krek12 Да, вам понадобится расширение Hako Mikan Lora Block Weight для использования этого расширения. Это потому, что это инструмент для визуальной настройки весов Lora, который можно настроить с помощью Lora Block Weight.
> > https://github.com/hako-mikan/sd-webui-lora-block-weight
> 
> then I don't know what's wrong with me. For the last couple of weeks I have been trying everything I have tried. I've even used different browsers. I still don't understand what's wrong.

What UI are you using? If it's Auto1111 is should still work, If its OLD forge (not the updated one) it should still work, But the new Forge don't work with block weights anymore. The extension is broken.

**Comment by nihedon** [comment]
@Krek12 
As @diodiogod mentioned, it seems that the behavior varies depending on the UI. I’ve fixed it so that it should work with Auto1111 and the New Forge. If it still doesn’t work, please create a new issue with details about the UI you’re using and any error logs. I’ll do my best to address the issue.
Thank you!
